### ISSUE TITLE
2 seperate uploads, only one green tick

### ISSUE THREAD

**Issue by validatingsenie** [benjaminchodroff/ConsensusLayerWithdrawalProtection#170]
Hi Team! I uploaded validators in two batches yesterday (27th of February). But only one of them have the green tick mark here https://github.com/benjaminchodroff/ConsensusLayerWithdrawalProtection/commits/main. Please confirm all validators will be submitted.

**Comment by benjaminchodroff** [comment]
I have provided more details in the pull request: https://github.com/benjaminchodroff/ConsensusLayerWithdrawalProtection/pull/167

If you need more validators to be uploaded, please open a new pull request. You can see all your validators have been included in the mainnet folder. It appears you have no further validators to upload. I'll close this issue as it appears to be solved.
